/**
 * Central catalog for app-launcher tiles (Odoo-style module grid).
 * permission: single key, or permissions: any-of list for visibility.
 */

export const APP_CATEGORIES = {
  sales: "Sales & CRM",
  billing: "Billing & GST",
  operations: "Operations",
  people: "People & HR",
  finance: "Finance",
  inventory: "Inventory",
  admin: "Administration",
};

export const CRM_APPS = [
  {
    id: "leads",
    label: "Leads",
    subtitle: "Enquiries & outreach",
    path: "/leads",
    permission: "leads.view",
    category: "sales",
    color: "#7c3aed",
    icon: "leads",
  },
  {
    id: "pipeline",
    label: "Pipeline",
    subtitle: "Deals by stage",
    path: "/pipeline",
    permission: "deals.view",
    category: "sales",
    color: "#2563eb",
    icon: "pipeline",
  },
  {
    id: "follow-ups",
    label: "Follow-ups",
    subtitle: "Calls & reminders",
    path: "/follow-ups",
    permission: "reminders.view",
    category: "sales",
    color: "#059669",
    icon: "followups",
  },
  {
    id: "contacts",
    label: "Contacts",
    subtitle: "Clients & stakeholders",
    path: "/contacts",
    permission: "contacts.view",
    category: "sales",
    color: "#0891b2",
    icon: "contacts",
  },
  {
    id: "client-notes",
    label: "Client notes",
    subtitle: "Conversation history",
    path: "/client-notes",
    permission: "client_notes.view",
    category: "sales",
    color: "#0d9488",
    icon: "notes",
  },
  {
    id: "quotations",
    label: "Quotations",
    subtitle: "Proposals & quotes",
    path: "/quotations",
    permission: "quotations.view",
    category: "billing",
    color: "#db2777",
    icon: "quotations",
  },
  {
    id: "invoices",
    label: "Invoices",
    subtitle: "GST-ready billing",
    path: "/invoices",
    permission: "invoices.view",
    category: "billing",
    color: "#e11d48",
    icon: "invoices",
  },
  {
    id: "payments",
    label: "Payments",
    subtitle: "Collections & dues",
    path: "/payments",
    permission: "payments.view",
    category: "billing",
    color: "#ea580c",
    icon: "payments",
  },
  {
    id: "tax-reports",
    label: "GST / Tax",
    subtitle: "Tax summaries",
    path: "/tax-reports",
    permissions: ["tax_reports.view", "reports.view_financial"],
    category: "billing",
    color: "#ca8a04",
    icon: "tax",
  },
  {
    id: "customer-ledger",
    label: "Customer ledger",
    subtitle: "Account statements",
    path: "/customer-ledger",
    permissions: ["customer_ledger.view", "invoices.view", "payments.view"],
    category: "billing",
    color: "#9333ea",
    icon: "ledger",
  },
  {
    id: "sales-orders",
    label: "Orders",
    subtitle: "Confirmed work",
    path: "/sales-orders",
    permission: "sales_orders.view",
    category: "operations",
    color: "#4f46e5",
    icon: "orders",
  },
  {
    id: "projects",
    label: "Projects",
    subtitle: "Tasks & delivery",
    path: "/projects",
    permission: "projects.view",
    category: "operations",
    color: "#0284c7",
    icon: "projects",
  },
  {
    id: "products",
    label: "Products",
    subtitle: "Services catalogue",
    path: "/products",
    permission: "products.view",
    category: "operations",
    color: "#16a34a",
    icon: "products",
  },
  {
    id: "documents",
    label: "Documents",
    subtitle: "Files & uploads",
    path: "/documents",
    permissions: ["files.view", "files.view_own"],
    category: "operations",
    color: "#64748b",
    icon: "documents",
  },
  {
    id: "website",
    label: "Website",
    subtitle: "Pages & leads",
    path: "/website",
    permission: "website.view",
    category: "sales",
    color: "#0ea5e9",
    icon: "branding",
  },
  {
    id: "ecommerce",
    label: "Online Store",
    subtitle: "Shop & web orders",
    path: "/ecommerce",
    permission: "ecommerce.view",
    category: "sales",
    color: "#ea580c",
    icon: "orders",
  },
  {
    id: "pos",
    label: "Point of Sale",
    subtitle: "Counter billing",
    path: "/pos",
    permission: "pos.view",
    category: "sales",
    color: "#16a34a",
    icon: "payments",
  },
  {
    id: "manufacturing",
    label: "Manufacturing",
    subtitle: "BOMs & work orders",
    path: "/manufacturing",
    permission: "manufacturing.view",
    category: "operations",
    color: "#b45309",
    icon: "inventory",
  },
  {
    id: "quality",
    label: "Quality Control",
    subtitle: "Inspections & CAPA",
    path: "/quality",
    permission: "quality.view",
    category: "operations",
    color: "#dc2626",
    icon: "approvals",
  },
  {
    id: "maintenance",
    label: "Maintenance",
    subtitle: "Assets & CMMS",
    path: "/maintenance",
    permission: "maintenance.view",
    category: "operations",
    color: "#0d9488",
    icon: "inventory",
  },
  {
    id: "field-service",
    label: "Field Service",
    subtitle: "Site visits & dispatch",
    path: "/field-service",
    permission: "field_service.view",
    category: "operations",
    color: "#2563eb",
    icon: "employees",
  },
  {
    id: "subscriptions",
    label: "Subscriptions",
    subtitle: "Recurring revenue & billing",
    path: "/subscriptions",
    permission: "subscriptions.view",
    category: "finance",
    color: "#7c3aed",
    icon: "invoices",
  },
  {
    id: "rental",
    label: "Rental",
    subtitle: "Assets, bookings & deposits",
    path: "/rental",
    permission: "rental.view",
    category: "operations",
    color: "#ea580c",
    icon: "inventory",
  },
  {
    id: "employees",
    label: "Employees",
    subtitle: "Team directory",
    path: "/employees",
    permission: "employees.view_all",
    category: "people",
    color: "#7c3aed",
    icon: "employees",
  },
  {
    id: "attendance",
    label: "Attendance",
    subtitle: "Check-in & roster",
    path: "/attendance",
    permission: "attendance.view",
    category: "people",
    color: "#22c55e",
    icon: "attendance",
  },
  {
    id: "leaves",
    label: "Leave",
    subtitle: "Apply & approve",
    path: "/leaves",
    permission: "leaves.view",
    category: "people",
    color: "#14b8a6",
    icon: "leave",
  },
  {
    id: "timesheets",
    label: "Timesheets",
    subtitle: "Billable hours",
    path: "/timesheets",
    permission: "timesheets.view",
    category: "people",
    color: "#3b82f6",
    icon: "timesheets",
  },
  {
    id: "payroll",
    label: "Payroll",
    subtitle: "Salary & payslips",
    path: "/payroll",
    permission: "payroll.view",
    category: "people",
    color: "#f43f5e",
    icon: "payroll",
  },
  {
    id: "recruitment",
    label: "Recruitment",
    subtitle: "Hiring pipeline",
    path: "/recruitment",
    permission: "recruitment.view",
    category: "people",
    color: "#a855f7",
    icon: "recruitment",
  },
  {
    id: "expenses",
    label: "Expenses",
    subtitle: "Claims & approvals",
    path: "/expenses",
    permission: "expenses.view",
    category: "finance",
    color: "#f97316",
    icon: "expenses",
  },
  {
    id: "vendor-bills",
    label: "Vendor bills",
    subtitle: "Payables",
    path: "/vendor-bills",
    permission: "vendor_bills.view",
    category: "finance",
    color: "#ef4444",
    icon: "vendorBills",
  },
  {
    id: "purchase-orders",
    label: "Purchase",
    subtitle: "PO & procurement",
    path: "/purchase-orders",
    permission: "purchase_orders.view",
    category: "finance",
    color: "#84cc16",
    icon: "purchase",
  },
  {
    id: "vendor-ledger",
    label: "Vendor ledger",
    subtitle: "Supplier accounts",
    path: "/vendor-ledger",
    permissions: ["vendor_ledger.view", "vendor_bills.view"],
    category: "finance",
    color: "#78716c",
    icon: "ledger",
  },
  {
    id: "pl-reports",
    label: "P&L reports",
    subtitle: "Profit & loss",
    path: "/pl-reports",
    permissions: ["pl_reports.view", "reports.view_financial"],
    category: "finance",
    color: "#6366f1",
    icon: "reports",
  },
  {
    id: "sales-reports",
    label: "Sales reports",
    subtitle: "Performance KPIs",
    path: "/sales-reports",
    permission: "reports.view",
    category: "finance",
    color: "#0ea5e9",
    icon: "reports",
  },
  {
    id: "ai-reports",
    label: "AI Reports",
    subtitle: "Plain-language insights",
    path: "/ai-reports",
    permission: "ai_reports.view",
    category: "finance",
    color: "#8b5cf6",
    icon: "reports",
  },
  {
    id: "workflows",
    label: "Workflow Builder",
    subtitle: "Triggers, conditions & actions",
    path: "/workflows",
    permission: "workflows.view",
    category: "operations",
    color: "#0891b2",
    icon: "approvals",
  },
  {
    id: "inventory",
    label: "Inventory",
    subtitle: "Stock on hand",
    path: "/inventory",
    permission: "inventory.view",
    category: "inventory",
    color: "#10b981",
    icon: "inventory",
  },
  {
    id: "stock-movements",
    label: "Stock in/out",
    subtitle: "Movements",
    path: "/stock-movements",
    permission: "stock_movements.view",
    category: "inventory",
    color: "#06b6d4",
    icon: "stock",
  },
  {
    id: "warehouses",
    label: "Warehouses",
    subtitle: "Locations",
    path: "/warehouses",
    permission: "warehouses.view",
    category: "inventory",
    color: "#8b5cf6",
    icon: "warehouse",
  },
  {
    id: "approvals",
    label: "Approvals",
    subtitle: "Pending actions",
    path: "/approvals",
    permission: "approvals.view",
    category: "operations",
    color: "#f59e0b",
    icon: "approvals",
  },
  {
    id: "chat",
    label: "Chat",
    subtitle: "Team messages",
    path: "/chat",
    permission: "chat.view",
    category: "operations",
    color: "#38bdf8",
    icon: "chat",
  },
  {
    id: "admin-users",
    label: "Users",
    subtitle: "Roles & access",
    path: "/admin/users",
    permission: "users.view",
    category: "admin",
    color: "#8b5cf6",
    icon: "users",
  },
  {
    id: "admin-company",
    label: "Company",
    subtitle: "Business profile",
    path: "/admin/company",
    permission: "company.view",
    category: "admin",
    color: "#3b82f6",
    icon: "company",
  },
  {
    id: "admin-branding",
    label: "Branding",
    subtitle: "Logo & letterhead",
    path: "/admin/branding",
    permission: "settings.edit",
    category: "admin",
    color: "#ec4899",
    icon: "branding",
  },
  {
    id: "admin-activity",
    label: "Activity log",
    subtitle: "Audit trail",
    path: "/admin/activity-logs",
    permission: "activity.view",
    category: "admin",
    color: "#64748b",
    icon: "activity",
  },
  {
    id: "admin-roles",
    label: "Roles",
    subtitle: "Permission matrix",
    path: "/admin/roles-matrix",
    permission: "roles.view",
    category: "admin",
    color: "#6366f1",
    icon: "roles",
  },
  {
    id: "admin-numbering",
    label: "Numbering",
    subtitle: "Invoice & quote IDs",
    path: "/admin/numbering-config",
    permission: "numbering_config.view",
    category: "admin",
    color: "#0ea5e9",
    icon: "numbering",
  },
  {
    id: "admin-system",
    label: "System config",
    subtitle: "Tax & defaults",
    path: "/admin/system-config",
    permission: "company.view",
    category: "admin",
    color: "#475569",
    icon: "settings",
  },
  {
    id: "admin-email-templates",
    label: "Email templates",
    subtitle: "Outbound messages",
    path: "/admin/email-templates",
    permission: "company.view",
    category: "admin",
    color: "#14b8a6",
    icon: "email",
  },
  {
    id: "send-notification",
    label: "Alerts",
    subtitle: "Notify team",
    path: "/send-notification",
    permission: "notifications.send",
    category: "admin",
    color: "#f43f5e",
    icon: "alerts",
  },
];

/** Featured modules on the public landing page (no auth required). */
export const LANDING_APPS = [
  { id: "leads", label: "CRM", subtitle: "Lead tracking", color: "#7c3aed", icon: "leads" },
  { id: "pipeline", label: "Pipeline", subtitle: "Deal stages", color: "#2563eb", icon: "pipeline" },
  { id: "follow-ups", label: "Follow-ups", subtitle: "WhatsApp-ready", color: "#059669", icon: "followups" },
  { id: "quotations", label: "Quotations", subtitle: "Service quotes", color: "#db2777", icon: "quotations" },
  { id: "invoices", label: "Invoices", subtitle: "GST documents", color: "#e11d48", icon: "invoices" },
  { id: "payments", label: "Payments", subtitle: "Dues & receipts", color: "#ea580c", icon: "payments" },
  { id: "tax", label: "GST", subtitle: "Tax reports", color: "#ca8a04", icon: "tax" },
  { id: "projects", label: "Projects", subtitle: "Tasks & delivery", color: "#0284c7", icon: "projects" },
  { id: "timesheets", label: "Timesheets", subtitle: "Billable hours", color: "#3b82f6", icon: "timesheets" },
  { id: "documents", label: "Documents", subtitle: "Files & proofs", color: "#64748b", icon: "documents" },
  { id: "employees", label: "HR", subtitle: "Team records", color: "#7c3aed", icon: "employees" },
  { id: "payroll", label: "Payroll", subtitle: "Payslips", color: "#f43f5e", icon: "payroll" },
  { id: "expenses", label: "Expenses", subtitle: "Claims", color: "#f97316", icon: "expenses" },
  { id: "inventory", label: "Inventory", subtitle: "For traders", color: "#10b981", icon: "inventory" },
  { id: "purchase", label: "Purchase", subtitle: "Vendor POs", color: "#84cc16", icon: "purchase" },
  { id: "reports", label: "Reports", subtitle: "Business KPIs", color: "#0ea5e9", icon: "reports" },
  { id: "contacts", label: "Contacts", subtitle: "Clients & NGOs", color: "#0891b2", icon: "contacts" },
  { id: "approvals", label: "Approvals", subtitle: "Workflows", color: "#f59e0b", icon: "approvals" },
];

export const LANDING_PORTALS = [
  {
    title: "Sales",
    description: "Leads, quotes & client follow-ups",
    path: "/sales-login",
    color: "#3b82f6",
    icon: "pipeline",
  },
  {
    title: "Accountant",
    description: "Invoices, GST & payments",
    path: "/accountant-login",
    color: "#f43f5e",
    icon: "invoices",
  },
  {
    title: "Employee",
    description: "Attendance, leave & timesheets",
    path: "/employee-login",
    color: "#22c55e",
    icon: "attendance",
  },
  {
    title: "Admin",
    description: "Users, settings & company",
    path: "/admin-login",
    color: "#8b5cf6",
    icon: "users",
  },
  {
    title: "Manager",
    description: "Team performance & reports",
    path: "/manager-login",
    color: "#06b6d4",
    icon: "reports",
  },
  {
    title: "User Portal",
    description: "Portal Sign In & Account Access",
    path: "/user-login",
    color: "#4f46e5",
    icon: "user",
  },
];

export function appVisible(app, hasPermission) {
  if (app.permission) return hasPermission(app.permission);
  if (app.permissions?.length) {
    return app.permissions.some((p) => hasPermission(p));
  }
  return true;
}

export function filterAppsByPermission(apps, hasPermission) {
  return apps.filter((app) => appVisible(app, hasPermission));
}

export function groupAppsByCategory(apps) {
  const groups = {};
  for (const app of apps) {
    const key = app.category || "other";
    if (!groups[key]) groups[key] = [];
    groups[key].push(app);
  }
  return groups;
}
