from __future__ import annotations

"""Level 1 permission definitions and default role mappings."""

PERMISSIONS = [
    # Profile (all staff + public user)
    ("profile.view", "View own profile", "profile"),
    ("profile.edit", "Edit own profile", "profile"),
    ("profile.change_password", "Change own password", "profile"),
    # Company
    ("company.view", "View company settings", "company"),
    ("company.edit", "Edit company settings", "company"),
    # User management
    ("users.view", "View staff users", "users"),
    ("users.create", "Create staff users", "users"),
    ("users.edit", "Edit staff users", "users"),
    ("users.reset_password", "Reset staff passwords", "users"),
    ("users.delete", "Delete staff users", "users"),
    ("activity.view", "View activity logs", "users"),
    # Roles & permissions
    ("roles.view", "View role permission matrix", "roles"),
    # Reserved for upcoming Level 1 modules
    ("contacts.view", "View contacts", "contacts"),
    ("contacts.create", "Create contacts", "contacts"),
    ("contacts.edit", "Edit contacts", "contacts"),
    ("contacts.delete", "Delete contacts", "contacts"),
    ("products.view", "View products", "products"),
    ("products.create", "Create products", "products"),
    ("products.edit", "Edit products", "products"),
    ("products.delete", "Delete products", "products"),
    ("leads.view", "View leads", "leads"),
    ("leads.create", "Create leads", "leads"),
    ("leads.edit", "Edit leads", "leads"),
    ("leads.assign", "Assign leads to staff", "leads"),
    ("deals.view", "View sales pipeline", "deals"),
    ("deals.create", "Create deals", "deals"),
    ("deals.edit", "Edit deals and move stages", "deals"),
    ("deals.assign", "Assign deals to staff", "deals"),
    ("quotations.view", "View quotations", "quotations"),
    ("quotations.create", "Create quotations", "quotations"),
    ("quotations.edit_draft", "Edit draft quotations", "quotations"),
    ("quotations.submit_approval", "Submit quotations for approval", "quotations"),
    ("quotations.approve", "Approve quotations", "quotations"),
    ("quotations.send", "Send quotations to clients", "quotations"),
    ("quotations.cancel", "Cancel quotations", "quotations"),
    ("quotations.accept_override", "Override client acceptance/rejection", "quotations"),
    ("quotations.manage_templates", "Manage quotation templates and settings", "quotations"),
    ("sales_orders.view", "View sales orders", "sales_orders"),
    ("sales_orders.create", "Create sales orders", "sales_orders"),
    ("sales_orders.edit_draft", "Edit draft sales orders", "sales_orders"),
    ("sales_orders.convert_from_quote", "Convert quotations to sales orders", "sales_orders"),
    ("sales_orders.confirm", "Confirm sales orders", "sales_orders"),
    ("sales_orders.update_progress", "Update order fulfillment progress", "sales_orders"),
    ("sales_orders.hold", "Place sales orders on hold", "sales_orders"),
    ("sales_orders.cancel", "Cancel sales orders", "sales_orders"),
    ("sales_orders.amend", "Amend confirmed sales orders", "sales_orders"),
    ("sales_orders.manage_settings", "Manage sales order settings", "sales_orders"),
    ("invoices.view", "View invoices", "invoices"),
    ("invoices.create", "Create invoices", "invoices"),
    ("invoices.edit_draft", "Edit draft invoices", "invoices"),
    ("invoices.generate_from_order", "Generate invoices from sales orders", "invoices"),
    ("invoices.review", "Review and approve invoices", "invoices"),
    ("invoices.issue", "Issue finalized invoices", "invoices"),
    ("invoices.send", "Send invoices to clients", "invoices"),
    ("invoices.record_payment", "Record invoice payments", "invoices"),
    ("invoices.create_adjustment", "Create invoice adjustments and credit notes", "invoices"),
    ("invoices.cancel", "Cancel invoices", "invoices"),
    ("invoices.write_off", "Write off invoice balances", "invoices"),
    ("invoices.manage_settings", "Manage invoice settings", "invoices"),
    ("client_notes.view", "View client notes", "client_notes"),
    ("client_notes.create", "Create client notes", "client_notes"),
    ("client_notes.edit_own", "Edit own client notes", "client_notes"),
    ("client_notes.edit_all", "Edit all client notes", "client_notes"),
    ("client_notes.delete", "Delete client notes", "client_notes"),
    ("client_notes.pin", "Pin client notes", "client_notes"),
    ("client_notes.view_sensitive", "View sensitive client notes", "client_notes"),
    ("client_notes.manage_followups", "Manage client note follow-ups", "client_notes"),
    ("client_notes.manage_settings", "Manage client note settings", "client_notes"),
    ("reports.view", "View own sales reports", "reports"),
    ("reports.view_team", "View team sales reports", "reports"),
    ("reports.view_company", "View company-wide sales reports", "reports"),
    ("reports.view_financial", "View financial revenue reports", "reports"),
    ("reports.export", "Export sales reports", "reports"),
    ("reports.manage_saved_views", "Manage saved report views", "reports"),
    ("tax_reports.view", "View GST / tax reports", "tax_reports"),
    ("tax_reports.view_sales", "View outward (sales) tax report", "tax_reports"),
    ("tax_reports.view_purchase", "View inward (purchase) tax report", "tax_reports"),
    ("tax_reports.view_summary", "View tax summary report", "tax_reports"),
    ("tax_reports.export", "Export GST / tax reports", "tax_reports"),
    ("tax_reports.manage_settings", "Manage tax report settings", "tax_reports"),
    ("customer_ledger.view", "View customer ledger", "customer_ledger"),
    ("customer_ledger.view_all", "View all customer ledgers", "customer_ledger"),
    ("customer_ledger.export", "Export customer ledger statements", "customer_ledger"),
    ("customer_ledger.manage_settings", "Manage customer ledger settings", "customer_ledger"),
    ("vendor_ledger.view", "View vendor ledger", "vendor_ledger"),
    ("vendor_ledger.view_all", "View all vendor ledgers", "vendor_ledger"),
    ("vendor_ledger.export", "Export vendor ledger statements", "vendor_ledger"),
    ("vendor_ledger.manage_settings", "Manage vendor ledger settings", "vendor_ledger"),
    ("pl_reports.view", "View P&L reports", "pl_reports"),
    ("pl_reports.export", "Export P&L reports", "pl_reports"),
    ("pl_reports.manage_settings", "Manage P&L report settings", "pl_reports"),
    ("expenses.view", "View expenses", "expenses"),
    ("expenses.create", "Create expenses", "expenses"),
    ("expenses.edit_own", "Edit own expenses", "expenses"),
    ("expenses.edit_all", "Edit all expenses", "expenses"),
    ("expenses.submit", "Submit expenses for approval", "expenses"),
    ("expenses.approve", "Approve expenses", "expenses"),
    ("expenses.reject", "Reject expenses", "expenses"),
    ("expenses.mark_paid", "Mark expenses as paid", "expenses"),
    ("expenses.delete", "Delete draft expenses", "expenses"),
    ("expenses.export", "Export expenses", "expenses"),
    ("expenses.manage_settings", "Manage expense settings", "expenses"),
    ("purchase_orders.view", "View purchase orders", "purchase_orders"),
    ("purchase_orders.create", "Create purchase orders", "purchase_orders"),
    ("purchase_orders.edit_own", "Edit own purchase orders", "purchase_orders"),
    ("purchase_orders.edit_all", "Edit all purchase orders", "purchase_orders"),
    ("purchase_orders.submit", "Submit purchase orders for approval", "purchase_orders"),
    ("purchase_orders.approve", "Approve purchase orders", "purchase_orders"),
    ("purchase_orders.reject", "Reject purchase orders", "purchase_orders"),
    ("purchase_orders.send", "Send purchase orders to vendors", "purchase_orders"),
    ("purchase_orders.record_receipt", "Record purchase order receipts", "purchase_orders"),
    ("purchase_orders.record_billing", "Record purchase order billing", "purchase_orders"),
    ("purchase_orders.close", "Close purchase orders", "purchase_orders"),
    ("purchase_orders.delete", "Delete draft purchase orders", "purchase_orders"),
    ("purchase_orders.export", "Export purchase orders", "purchase_orders"),
    ("purchase_orders.manage_settings", "Manage purchase order settings", "purchase_orders"),
    ("vendor_bills.view", "View vendor bills", "vendor_bills"),
    ("vendor_bills.create", "Create vendor bills", "vendor_bills"),
    ("vendor_bills.edit_own", "Edit own vendor bills", "vendor_bills"),
    ("vendor_bills.edit_all", "Edit all vendor bills", "vendor_bills"),
    ("vendor_bills.submit", "Submit vendor bills for approval", "vendor_bills"),
    ("vendor_bills.approve", "Approve vendor bills", "vendor_bills"),
    ("vendor_bills.reject", "Reject vendor bills", "vendor_bills"),
    ("vendor_bills.record_payment", "Record vendor bill payments", "vendor_bills"),
    ("vendor_bills.cancel", "Cancel vendor bills", "vendor_bills"),
    ("vendor_bills.delete", "Delete draft vendor bills", "vendor_bills"),
    ("vendor_bills.export", "Export vendor bills", "vendor_bills"),
    ("vendor_bills.manage_settings", "Manage vendor bill settings", "vendor_bills"),
    ("inventory.view", "View inventory", "inventory"),
    ("inventory.enable_tracking", "Enable inventory tracking on products", "inventory"),
    ("inventory.record_opening", "Record opening stock", "inventory"),
    ("inventory.record_purchase", "Record purchase stock movements", "inventory"),
    ("inventory.record_sale", "Record sale stock movements", "inventory"),
    ("inventory.record_damage", "Record damage stock movements", "inventory"),
    ("inventory.adjust", "Record inventory adjustments", "inventory"),
    ("inventory.override_negative", "Override negative stock blocks", "inventory"),
    ("inventory.export", "Export inventory data", "inventory"),
    ("inventory.manage_settings", "Manage inventory settings", "inventory"),
    ("stock_movements.view", "View stock in/out ledger", "stock_movements"),
    ("stock_movements.record_in", "Record stock in movements", "stock_movements"),
    ("stock_movements.record_out", "Record stock out movements", "stock_movements"),
    ("stock_movements.override_negative", "Override negative stock on stock out", "stock_movements"),
    ("stock_movements.export", "Export stock movement data", "stock_movements"),
    ("stock_movements.manage_settings", "Manage stock movement settings", "stock_movements"),
    ("warehouses.view", "View warehouses and locations", "warehouses"),
    ("warehouses.manage_locations", "Manage warehouse locations", "warehouses"),
    ("warehouses.view_stock", "View stock by location", "warehouses"),
    ("warehouses.record_receipt", "Record warehouse receipts", "warehouses"),
    ("warehouses.record_issue", "Record warehouse issues", "warehouses"),
    ("warehouses.record_damage", "Record warehouse damage", "warehouses"),
    ("warehouses.adjust", "Record warehouse adjustments", "warehouses"),
    ("warehouses.transfer", "Transfer stock between locations", "warehouses"),
    ("warehouses.override_negative", "Override negative location stock blocks", "warehouses"),
    ("warehouses.export", "Export warehouse data", "warehouses"),
    ("warehouses.manage_settings", "Manage warehouse settings", "warehouses"),
    ("reminders.view", "View follow-up reminders", "reminders"),
    ("reminders.create", "Create follow-up reminders", "reminders"),
    ("reminders.edit", "Edit and complete reminders", "reminders"),
    ("payments.view", "View payments and outstanding balances", "payments"),
    ("dashboard.view", "View dashboard KPIs", "dashboard"),

    ("projects.view", "View projects", "projects"),
    ("projects.view_all", "View all company projects", "projects"),
    ("projects.create", "Create projects", "projects"),
    ("projects.edit", "Edit project details and team", "projects"),
    ("projects.manage_tasks", "Manage project tasks", "projects"),
    ("projects.close", "Complete, hold, or cancel projects", "projects"),
    ("projects.delete", "Delete draft projects", "projects"),
    ("projects.export", "Export project task lists", "projects"),

    ("leaves.view", "View own leave requests", "leaves"),
    ("leaves.view_all", "View all company leave requests", "leaves"),
    ("leaves.create", "Create and submit leave requests", "leaves"),
    ("leaves.edit_own", "Edit own draft or rejected leave requests", "leaves"),
    ("leaves.cancel_own", "Cancel own draft or pending leave requests", "leaves"),
    ("leaves.approve", "Approve or reject leave requests", "leaves"),
    ("leaves.cancel_all", "Cancel any leave request", "leaves"),
    ("leaves.export", "Export leave data", "leaves"),

    ("timesheets.view", "View own timesheet entries", "timesheets"),
    ("timesheets.view_all", "View all company timesheet entries", "timesheets"),
    ("timesheets.create", "Create timesheet entries", "timesheets"),
    ("timesheets.edit_own", "Edit own draft or rejected entries", "timesheets"),
    ("timesheets.submit", "Submit timesheet entries for approval", "timesheets"),
    ("timesheets.approve", "Approve or reject timesheet entries", "timesheets"),
    ("timesheets.delete_own", "Delete own draft timesheet entries", "timesheets"),
    ("timesheets.export", "Export timesheet data", "timesheets"),

    ("employees.view", "View own employee profile", "employees"),
    ("employees.view_all", "View all employee profiles", "employees"),
    ("employees.edit", "Edit employee HR profiles", "employees"),
    ("employees.export", "Export employee data", "employees"),

    ("attendance.view", "View own attendance", "attendance"),
    ("attendance.view_all", "View team attendance", "attendance"),
    ("attendance.record", "Record attendance for team", "attendance"),
    ("attendance.check_in", "Check in and check out", "attendance"),
    ("attendance.export", "Export attendance data", "attendance"),

    ("recruitment.view", "View recruitment pipeline", "recruitment"),
    ("recruitment.manage", "Manage jobs and applicants", "recruitment"),
    ("recruitment.export", "Export recruitment data", "recruitment"),

    ("payroll.view", "View own payslips", "payroll"),
    ("payroll.view_all", "View all payslips", "payroll"),
    ("payroll.generate", "Generate payslips", "payroll"),
    ("payroll.mark_paid", "Mark payslips as paid", "payroll"),
    ("payroll.export", "Export payroll data", "payroll"),

    ("approvals.view", "View unified approval hub", "approvals"),

    ("chat.view", "View internal chat", "chat"),
    ("chat.send", "Send chat messages", "chat"),

    ("notifications.view", "View in-app notifications", "notifications"),
    ("notifications.send", "Send notifications to staff by role", "notifications"),

    ("settings.view", "View system settings", "settings"),
    ("settings.edit", "Edit system settings", "settings"),
    ("numbering_config.view", "View numbering configurations", "numbering_config"),
    ("numbering_config.create", "Create numbering configurations", "numbering_config"),
    ("numbering_config.edit", "Edit numbering configurations", "numbering_config"),
    ("numbering_config.delete", "Delete numbering configurations", "numbering_config"),
    # Files
    ("files.upload", "Upload files", "files"),
    ("files.view", "View all files", "files"),
    ("files.view_own", "View own files", "files"),
    ("files.download", "Download all files", "files"),
    ("files.download_own", "Download own files", "files"),
    ("files.delete", "Delete files", "files"),
    # Website Builder
    ("website.view", "View website builder and public site settings", "website"),
    ("website.manage", "Create and edit pages, blog drafts, and forms", "website"),
    ("website.publish", "Publish and unpublish website content", "website"),
    ("website.delete", "Delete or archive website content", "website"),
    ("website.forms", "Manage forms and view submissions", "website"),
    # eCommerce
    ("ecommerce.view", "View online store dashboard and orders", "ecommerce"),
    ("ecommerce.manage_orders", "Update order fulfillment and cancel orders", "ecommerce"),
    ("ecommerce.manage_returns", "Approve and process returns", "ecommerce"),
    ("ecommerce.manage_catalog", "Manage products sold online", "ecommerce"),
    ("ecommerce.manage_settings", "Configure store settings", "ecommerce"),
    ("ecommerce.record_payment", "Record payments and refunds for web orders", "ecommerce"),
    # POS
    ("pos.view", "View POS dashboard, bills, and sessions", "pos"),
    ("pos.bill", "Use POS terminal and complete sales", "pos"),
    ("pos.hold", "Hold and recall POS carts", "pos"),
    ("pos.discount", "Apply POS discounts", "pos"),
    ("pos.void", "Void POS bills", "pos"),
    ("pos.return", "Process POS returns", "pos"),
    ("pos.manage_sessions", "Open, close, and audit register sessions", "pos"),
    ("pos.manage_catalog", "Manage products sold at POS", "pos"),
    ("pos.manage_settings", "Configure POS registers and settings", "pos"),
    # Manufacturing / MRP
    ("manufacturing.view", "View manufacturing dashboard and work orders", "manufacturing"),
    ("manufacturing.manage_bom", "Create and edit bills of materials", "manufacturing"),
    ("manufacturing.create_wo", "Create work orders", "manufacturing"),
    ("manufacturing.release_wo", "Release work orders for production", "manufacturing"),
    ("manufacturing.issue_materials", "Issue raw materials to work orders", "manufacturing"),
    ("manufacturing.receive_fg", "Receive finished goods from production", "manufacturing"),
    ("manufacturing.quality", "Perform quality inspections", "manufacturing"),
    ("manufacturing.cancel_wo", "Cancel work orders", "manufacturing"),
    ("manufacturing.manage_settings", "Configure manufacturing settings", "manufacturing"),
    # Quality Control
    ("quality.view", "View quality dashboard, inspections, and alerts", "quality"),
    ("quality.inspect", "Execute and submit quality inspections", "quality"),
    ("quality.manage_templates", "Manage inspection points and checklist templates", "quality"),
    ("quality.waive", "Waive failed inspections", "quality"),
    ("quality.manage_capa", "Manage corrective actions", "quality"),
    ("quality.manage_alerts", "Acknowledge and resolve quality alerts", "quality"),
    ("quality.manage_settings", "Configure quality control settings", "quality"),
    # Maintenance / CMMS
    ("maintenance.view", "View maintenance dashboard, assets, and work orders", "maintenance"),
    ("maintenance.manage_assets", "Create and edit equipment assets", "maintenance"),
    ("maintenance.create_wo", "Create maintenance work orders", "maintenance"),
    ("maintenance.execute_wo", "Execute and complete maintenance work orders", "maintenance"),
    ("maintenance.issue_parts", "Issue spare parts to maintenance work orders", "maintenance"),
    ("maintenance.cancel_wo", "Cancel maintenance work orders", "maintenance"),
    ("maintenance.manage_settings", "Configure maintenance module settings", "maintenance"),
    # Field Service
    ("field_service.view", "View field service dashboard, orders, and schedule", "field_service"),
    ("field_service.create", "Create field service orders", "field_service"),
    ("field_service.dispatch", "Assign and schedule field service orders", "field_service"),
    ("field_service.execute", "Execute and complete field service visits", "field_service"),
    ("field_service.issue_parts", "Issue parts to field service orders", "field_service"),
    ("field_service.cancel", "Cancel field service orders", "field_service"),
    ("field_service.manage_settings", "Configure field service module settings", "field_service"),
    # Subscriptions
    ("subscriptions.view", "View subscriptions dashboard, plans, and subscribers", "subscriptions"),
    ("subscriptions.manage_plans", "Create and edit subscription plans", "subscriptions"),
    ("subscriptions.create", "Create customer subscriptions", "subscriptions"),
    ("subscriptions.bill", "Run billing and generate renewal invoices", "subscriptions"),
    ("subscriptions.cancel", "Cancel customer subscriptions", "subscriptions"),
    ("subscriptions.change_plan", "Upgrade or downgrade subscriptions", "subscriptions"),
    ("subscriptions.manage_settings", "Configure subscription module settings", "subscriptions"),
    # Rental Management
    ("rental.view", "View rental dashboard, calendar, assets, and contracts", "rental"),
    ("rental.manage_assets", "Create and edit rentable assets", "rental"),
    ("rental.create", "Create draft rental contracts", "rental"),
    ("rental.confirm", "Confirm bookings and reserve calendar", "rental"),
    ("rental.dispatch", "Mark rental delivery dispatched or delivered", "rental"),
    ("rental.process_return", "Process returns and close rental contracts", "rental"),
    ("rental.manage_deposits", "Record deposit received, refund, and deductions", "rental"),
    ("rental.cancel", "Cancel rental contracts", "rental"),
    ("rental.manage_settings", "Configure rental module settings", "rental"),
    # AI Reports
    ("ai_reports.view", "View AI Reports hub and insight history", "ai_reports"),
    ("ai_reports.generate", "Generate plain-language insight briefs", "ai_reports"),
    ("ai_reports.manage_settings", "Configure AI Reports module settings", "ai_reports"),
    # Workflow Builder
    ("workflows.view", "View Workflow Builder hub and run history", "workflows"),
    ("workflows.create", "Create automation workflows", "workflows"),
    ("workflows.edit", "Edit automation workflows", "workflows"),
    ("workflows.activate", "Activate and deactivate workflows", "workflows"),
    ("workflows.delete", "Delete inactive workflows", "workflows"),
    ("workflows.manage_settings", "Configure Workflow Builder module settings", "workflows"),
    ("workflows.test", "Dry-run test workflows", "workflows"),
    # Marketing Automation
    ("marketing.view", "View marketing campaigns and enrollments", "marketing"),
    ("marketing.create", "Create marketing campaigns", "marketing"),
    ("marketing.edit", "Edit draft marketing campaigns", "marketing"),
    ("marketing.activate", "Activate and pause campaigns", "marketing"),
    ("marketing.run", "Process due campaign steps", "marketing"),
    ("marketing.manage_settings", "Configure marketing module settings", "marketing"),
    # AI Assistant
    ("ai_assistant.view", "View AI Assistant sessions", "ai_assistant"),
    ("ai_assistant.chat", "Chat with AI Assistant", "ai_assistant"),
    ("ai_assistant.manage_settings", "Configure AI Assistant settings", "ai_assistant"),
    # API & App Marketplace
    ("marketplace.view", "View integration catalog and marketplace hub", "marketplace"),
    ("marketplace.install", "Install and uninstall integrations", "marketplace"),
    ("marketplace.manage_keys", "Create and revoke API keys", "marketplace"),
    ("marketplace.manage_webhooks", "Manage outbound webhooks", "marketplace"),
    ("marketplace.manage_settings", "Configure marketplace settings", "marketplace"),
]

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "Admin": [code for code, _, _ in PERMISSIONS],
    "Manager": [
        "profile.view",
        "profile.edit",
        "profile.change_password",
        "contacts.view",
        "contacts.create",
        "contacts.edit",
        "products.view",
        "leads.view",
        "leads.create",
        "leads.edit",
        "leads.assign",
        "deals.view",
        "deals.create",
        "deals.edit",
        "deals.assign",
        "quotations.view",
        "quotations.create",
        "quotations.edit_draft",
        "quotations.submit_approval",
        "quotations.approve",
        "quotations.send",
        "quotations.cancel",
        "quotations.accept_override",
        "sales_orders.view",
        "sales_orders.create",
        "sales_orders.edit_draft",
        "sales_orders.convert_from_quote",
        "sales_orders.confirm",
        "sales_orders.update_progress",
        "sales_orders.hold",
        "sales_orders.cancel",
        "sales_orders.amend",
        "invoices.view",
        "invoices.create",
        "invoices.edit_draft",
        "invoices.generate_from_order",
        "invoices.review",
        "invoices.issue",
        "invoices.send",
        "invoices.record_payment",
        "invoices.create_adjustment",
        "invoices.cancel",
        "invoices.write_off",
        "client_notes.view",
        "client_notes.create",
        "client_notes.edit_own",
        "client_notes.edit_all",
        "client_notes.delete",
        "client_notes.pin",
        "client_notes.view_sensitive",
        "client_notes.manage_followups",
        "reports.view",
        "reports.view_team",
        "reports.view_company",
        "reports.view_financial",
        "reports.export",
        "tax_reports.view",
        "tax_reports.view_sales",
        "tax_reports.view_purchase",
        "tax_reports.view_summary",
        "tax_reports.export",
        "customer_ledger.view",
        "customer_ledger.view_all",
        "customer_ledger.export",
        "vendor_ledger.view",
        "vendor_ledger.view_all",
        "vendor_ledger.export",
        "pl_reports.view",
        "pl_reports.export",
        "expenses.view",
        "expenses.create",
        "expenses.edit_own",
        "expenses.edit_all",
        "expenses.submit",
        "expenses.approve",
        "expenses.reject",
        "expenses.mark_paid",
        "expenses.delete",
        "expenses.export",
        "projects.view",
        "projects.view_all",
        "projects.create",
        "projects.edit",
        "projects.manage_tasks",
        "projects.close",
        "projects.delete",
        "projects.export",
        "leaves.view",
        "leaves.view_all",
        "leaves.create",
        "leaves.edit_own",
        "leaves.cancel_own",
        "leaves.approve",
        "leaves.cancel_all",
        "leaves.export",
        "timesheets.view",
        "timesheets.view_all",
        "timesheets.create",
        "timesheets.edit_own",
        "timesheets.submit",
        "timesheets.approve",
        "timesheets.export",
        "employees.view",
        "employees.view_all",
        "employees.edit",
        "employees.export",
        "attendance.view",
        "attendance.view_all",
        "attendance.record",
        "attendance.check_in",
        "attendance.export",
        "recruitment.view",
        "recruitment.manage",
        "recruitment.export",
        "payroll.view",
        "payroll.view_all",
        "payroll.generate",
        "payroll.mark_paid",
        "payroll.export",
        "approvals.view",
        "chat.view",
        "chat.send",
        "notifications.view",
        "notifications.send",
        "purchase_orders.view",
        "purchase_orders.create",
        "purchase_orders.edit_own",
        "purchase_orders.edit_all",
        "purchase_orders.submit",
        "purchase_orders.approve",
        "purchase_orders.reject",
        "purchase_orders.send",
        "purchase_orders.record_receipt",
        "purchase_orders.record_billing",
        "purchase_orders.close",
        "purchase_orders.delete",
        "purchase_orders.export",
        "vendor_bills.view",
        "vendor_bills.create",
        "vendor_bills.edit_own",
        "vendor_bills.edit_all",
        "vendor_bills.submit",
        "vendor_bills.approve",
        "vendor_bills.reject",
        "vendor_bills.record_payment",
        "vendor_bills.cancel",
        "vendor_bills.delete",
        "vendor_bills.export",
        "inventory.view",
        "inventory.enable_tracking",
        "inventory.record_opening",
        "inventory.record_purchase",
        "inventory.record_sale",
        "inventory.record_damage",
        "inventory.adjust",
        "inventory.override_negative",
        "inventory.export",
        "stock_movements.view",
        "stock_movements.record_in",
        "stock_movements.record_out",
        "stock_movements.override_negative",
        "stock_movements.export",
        "warehouses.view",
        "warehouses.manage_locations",
        "warehouses.view_stock",
        "warehouses.record_receipt",
        "warehouses.record_issue",
        "warehouses.record_damage",
        "warehouses.adjust",
        "warehouses.transfer",
        "warehouses.override_negative",
        "warehouses.export",
        "reminders.view",
        "reminders.create",
        "reminders.edit",
        "payments.view",
        "dashboard.view",
        "files.upload",
        "files.view",
        "files.download",
        "files.delete",
        "website.view",
        "website.manage",
        "website.publish",
        "website.forms",
        "ecommerce.view",
        "ecommerce.manage_orders",
        "ecommerce.manage_returns",
        "ecommerce.manage_catalog",
        "ecommerce.record_payment",
        "pos.view",
        "pos.bill",
        "pos.hold",
        "pos.discount",
        "pos.void",
        "pos.return",
        "pos.manage_sessions",
        "pos.manage_catalog",
        "manufacturing.view",
        "manufacturing.manage_bom",
        "manufacturing.create_wo",
        "manufacturing.release_wo",
        "manufacturing.issue_materials",
        "manufacturing.receive_fg",
        "manufacturing.quality",
        "manufacturing.cancel_wo",
        "manufacturing.manage_settings",
        "quality.view",
        "quality.inspect",
        "quality.manage_templates",
        "quality.waive",
        "quality.manage_capa",
        "quality.manage_alerts",
        "quality.manage_settings",
        "maintenance.view",
        "maintenance.manage_assets",
        "maintenance.create_wo",
        "maintenance.execute_wo",
        "maintenance.issue_parts",
        "maintenance.cancel_wo",
        "field_service.view",
        "field_service.create",
        "field_service.dispatch",
        "field_service.execute",
        "field_service.issue_parts",
        "field_service.cancel",
        "subscriptions.view",
        "subscriptions.manage_plans",
        "subscriptions.create",
        "subscriptions.bill",
        "subscriptions.cancel",
        "subscriptions.change_plan",
        "rental.view",
        "rental.manage_assets",
        "rental.create",
        "rental.confirm",
        "rental.dispatch",
        "rental.process_return",
        "rental.manage_deposits",
        "rental.cancel",
        "profile.view",
        "profile.edit",
        "profile.change_password",
        "contacts.view",
        "products.view",
        "leads.view",
        "deals.view",
        "quotations.view",
        "quotations.create",
        "quotations.edit_draft",
        "quotations.submit_approval",
        "quotations.send",
        "sales_orders.view",
        "sales_orders.create",
        "sales_orders.edit_draft",
        "sales_orders.convert_from_quote",
        "sales_orders.confirm",
        "invoices.view",
        "invoices.create",
        "invoices.edit_draft",
        "invoices.generate_from_order",
        "client_notes.view",
        "client_notes.create",
        "client_notes.edit_own",
        "client_notes.pin",
        "client_notes.manage_followups",
        "reports.view",
        "expenses.view",
        "expenses.create",
        "expenses.edit_own",
        "expenses.submit",
        "projects.view",
        "projects.manage_tasks",
        "leaves.view",
        "leaves.create",
        "leaves.edit_own",
        "leaves.cancel_own",
        "timesheets.view",
        "timesheets.create",
        "timesheets.edit_own",
        "timesheets.submit",
        "timesheets.delete_own",
        "employees.view",
        "attendance.view",
        "attendance.check_in",
        "recruitment.view",
        "payroll.view",
        "approvals.view",
        "chat.view",
        "chat.send",
        "notifications.view",
        "notifications.send",
        "purchase_orders.view",
        "purchase_orders.create",
        "purchase_orders.edit_own",
        "purchase_orders.submit",
        "purchase_orders.record_receipt",
        "vendor_bills.view",
        "vendor_bills.create",
        "vendor_bills.edit_own",
        "vendor_bills.submit",
        "inventory.view",
        "inventory.enable_tracking",
        "inventory.record_opening",
        "inventory.record_purchase",
        "inventory.record_sale",
        "inventory.record_damage",
        "stock_movements.view",
        "stock_movements.record_in",
        "stock_movements.record_out",
        "warehouses.view",
        "warehouses.view_stock",
        "warehouses.record_receipt",
        "warehouses.record_issue",
        "warehouses.record_damage",
        "reminders.view",
        "reminders.create",
        "reminders.edit",
        "payments.view",
        "dashboard.view",
        "notifications.view",
        "notifications.send",
        "files.upload",
        "files.view_own",
        "files.download_own",
        "ai_reports.view",
        "ai_reports.generate",
        "workflows.view",
        "marketing.view",
        "marketing.create",
        "marketing.edit",
        "marketing.activate",
        "marketing.run",
        "ai_assistant.view",
        "ai_assistant.chat",
        "marketplace.view",
        "marketplace.install",
        "marketplace.manage_keys",
        "marketplace.manage_webhooks",

    ],
    "Sales": [
        "profile.view",
        "profile.edit",
        "profile.change_password",
        "dashboard.view",
        "notifications.view",
        "notifications.send",
        "contacts.view",
        "contacts.create",
        "contacts.edit",
        "products.view",
        "leads.view",
        "leads.create",
        "leads.edit",
        "leads.assign",
        "deals.view",
        "deals.create",
        "deals.edit",
        "deals.assign",
        "quotations.view",
        "quotations.create",
        "quotations.edit_draft",
        "quotations.submit_approval",
        "quotations.send",
        "sales_orders.view",
        "sales_orders.create",
        "sales_orders.edit_draft",
        "sales_orders.convert_from_quote",
        "sales_orders.confirm",
        "invoices.view",
        "invoices.create",
        "invoices.edit_draft",
        "invoices.generate_from_order",
        "client_notes.view",
        "client_notes.create",
        "client_notes.edit_own",
        "client_notes.pin",
        "client_notes.manage_followups",
        "reminders.view",
        "reminders.create",
        "reminders.edit",
        "payments.view",
        "reports.view",
        "projects.view",
        "projects.manage_tasks",
        "leaves.view",
        "leaves.create",
        "leaves.edit_own",
        "leaves.cancel_own",
        "timesheets.view",
        "timesheets.create",
        "timesheets.edit_own",
        "timesheets.submit",
        "timesheets.delete_own",
        "files.upload",
        "files.view_own",
        "files.download_own",
        "website.view",
        "website.manage",
        "website.forms",
        "ecommerce.view",
        "ecommerce.manage_orders",
        "ecommerce.manage_catalog",
        "pos.view",
        "pos.bill",
        "pos.hold",
        "pos.manage_catalog",
        "manufacturing.view",
        "manufacturing.create_wo",
        "quality.view",
        "maintenance.view",
        "field_service.view",
        "field_service.create",
        "subscriptions.view",
        "subscriptions.create",
        "subscriptions.change_plan",
        "rental.view",
        "rental.create",
        "rental.confirm",
        "ai_reports.view",
        "marketing.view",
        "marketing.run",
        "ai_assistant.view",
        "ai_assistant.chat",
    ],
    "Accountant": [
        "profile.view",
        "profile.edit",
        "profile.change_password",
        "dashboard.view",
        "notifications.view",
        "notifications.send",
        "contacts.view",
        "products.view",
        "invoices.view",
        "invoices.review",
        "invoices.issue",
        "invoices.send",
        "invoices.record_payment",
        "invoices.create_adjustment",
        "payments.view",
        "expenses.view",
        "expenses.approve",
        "expenses.reject",
        "expenses.mark_paid",
        "expenses.export",
        "purchase_orders.view",
        "purchase_orders.approve",
        "purchase_orders.reject",
        "vendor_bills.view",
        "vendor_bills.approve",
        "vendor_bills.reject",
        "vendor_bills.record_payment",
        "tax_reports.view",
        "tax_reports.view_sales",
        "tax_reports.view_purchase",
        "tax_reports.view_summary",
        "tax_reports.export",
        "customer_ledger.view",
        "customer_ledger.view_all",
        "customer_ledger.export",
        "vendor_ledger.view",
        "vendor_ledger.view_all",
        "vendor_ledger.export",
        "pl_reports.view",
        "pl_reports.export",
        "ecommerce.view",
        "ecommerce.manage_returns",
        "ecommerce.record_payment",
        "pos.view",
        "pos.return",
        "pos.manage_sessions",
        "manufacturing.view",
        "quality.view",
        "maintenance.view",
        "field_service.view",
        "subscriptions.view",
        "subscriptions.bill",
        "rental.view",
        "rental.manage_deposits",
        "payroll.view",
        "payroll.view_all",
        "reports.view_financial",
        "settings.view",
        "numbering_config.view",
        "files.upload",
        "files.view",
        "files.download",
        "ai_reports.view",
        "ai_reports.generate",
    ],
    "Employee": [
        "profile.view",
        "profile.edit",
        "profile.change_password",
        "dashboard.view",
        "attendance.view",
        "attendance.check_in",
        "leaves.view",
        "leaves.create",
        "leaves.edit_own",
        "leaves.cancel_own",
        "timesheets.view",
        "timesheets.create",
        "timesheets.edit_own",
        "timesheets.submit",
        "timesheets.delete_own",
        "projects.view",
        "projects.manage_tasks",
        "payroll.view",
        "chat.view",
        "chat.send",
        "notifications.view",
        "notifications.send",
        "files.upload",
        "files.view_own",
        "files.download_own",
        "website.view",
        "ecommerce.view",
        "pos.view",
        "pos.bill",
        "pos.hold",
        "manufacturing.view",
        "manufacturing.issue_materials",
        "manufacturing.receive_fg",
        "manufacturing.quality",
        "quality.view",
        "quality.inspect",
        "maintenance.view",
        "maintenance.create_wo",
        "maintenance.execute_wo",
        "maintenance.issue_parts",
        "field_service.view",
        "field_service.execute",
        "field_service.issue_parts",
        "subscriptions.view",
        "rental.view",
        "rental.dispatch",
        "rental.process_return",
    ],
    "User": [
        "profile.view",
        "profile.edit",
        "profile.change_password",
        "notifications.view",
    ],
}
